# Generated by Django 3.2.7 on 2021-09-29 23:51

from django.db import migrations, models
import djangogramm.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dguser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=djangogramm.utilities.get_timestamp_path, verbose_name='user avatar'),
        ),
    ]
