# Generated by Django 3.2.7 on 2021-10-02 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangogramm.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0002_alter_dguser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DgPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=djangogramm.utilities.get_timestamp_path, verbose_name='post image')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('dg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
