# Generated by Django 3.2.7 on 2021-10-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0003_dgpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgpost',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='publication date'),
        ),
    ]
