# Generated by Django 3.2.7 on 2021-10-10 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0004_alter_dgpost_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dgpost',
            options={'ordering': ['-pub_date']},
        ),
    ]
